---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: fedora-21

suites:
  - name: default
    run_list:
      - recipe[socrates::default]
    attributes:
