language: ruby
rvm:
- 2.2.1
install: gem install fpm package_cloud
script: make test_ci
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk
    - rpm
before_deploy: make package
deploy:
  provider: packagecloud
  username: jonathanporta
  repository: socrates
  dist: fedora/21
  skip_cleanup: true
  token:
    secure: KyZE2VU49Ymxk2VMNB2Ty4GGURDQ7jbvm8L0wSFjmgEQ1QLJFK6wuDqyayb9SG0VyZ7JzdSjAJAyP2KIgfmSYn7vZrEPFx4g1b1KYRPWT0StgPxXYoWcBsHx4l64EXo60sSBHZIi9JG49LUtKrOIZLsEFK/9rjBkUOkPdcLizfKDhn5rJQV1qWbbriaWcwHQN+Qjenb0e+9ss1fPUWsFU3Me3FS3jCHTfqgi8t+gnTce48vPO4qguBol7RWHTRSqU111DhkfDDzuA8xfHRupiJQ9D5CSLyOFh+iQIxQT6CDjMCGlukN+FidL1M46FcA2wylRe7012PeBpXlqBxs4XQdtyyp0f3myk7hucb5pbFQn+CGVZRXrEAPHLaWsvd+ePwlX0Vl1b1SjgMpjkRkaeETv1wJ3d60/Za5J5/+asnNXwEzH6jvvkgtQASFhMScp3P2H2I0uuz2p9GmDcD8rDnMKbGWlRySKkRRmkrUEMeFGTrupCDaYRhJnVE6YP1eTh56vXQsTMt39SKCPP9FMd39E3iPHuvzv2xxhslpp4spCv/NMqAU2yBsbph5Vwz6EV+GmiUjvafgJly6eP6Ric8mnLMP/w523P3uAY60XXPUC6PrGzoAuh11kmYtpKHg+eQ0UvoyMJfqRGMdcPTqrcgF3Um2GUKOaKAQVUFkG8HA=
notifications:
  slack:
    secure: RDjJviCamTFBua6yeNSkuZw23E7XIZslDsJdll+reJ+oTvwwT/2njcp8GZECEwUK0kTqeKnWvbidkScAoy6sQzdy25mLreMOpAZt5yLY+Eoq/KhUEj3wW5qoGxCu/GVSif0OiDnE4UU/r1n3ByzavYjCt4lqC9mT0LRgGfzd/JZ3DzbDRLWBl+n8f1EYbkwKH4KtCQLVnXsazWo+fEk6dJorIXmPp6GI1FVdz7/Wq/cJRA0PmvGOqYjhgXq+4F6jH6TWNxmyEi3VgB4CkT5vQLAvnQwyb+Mgi4u15cd6V2wqSFAMYIEI43NlrXIikzdTBuJhMWD49N73z4ytTkWE7haxDSModAMM9JBTR0wRsWyUKSAPFpdhXcURLWfOqG5so7M8m+ZjU8E/Pu/RyNXTUK31tU1qod+fDvAek6/o3jFOcMUtdYtnGa/924hk6mSvB8vmrIij9EK49UQSk4KMWIOfDFdu380V/RN6BMB0nGenOKc/72MfEP+uZ/2EVT2RLuBw/WtKZoLEoJiVCtY911P+Wa3HEOSZZyyDbQGDwfwuVY+EHrSnVrbiSkjxGDfnOtjeQTxGm5iMIactEcpJR4HaQN8iI7YqppeWNghmCIhmqMP6xH5zHuAgR+9X6iERk6bS/0J7bU4uyCHy3ANAv9E7ggX8glIL8J8E6v/Gd+8=
