name 'socrates'
maintainer 'Jonathan Porta'
maintainer_email 'jonathan@jonathanPorta.com'
license 'WTFPL'
description 'Installs/Configures socrates'
long_description 'Installs/Configures socrates'
version '0.0.1'

depends 'porta_user'
depends 'openssh'
